# Generated by Django 5.1.6 on 2025-04-08 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthsymptom',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='healthsymptom',
            name='symptom',
        ),
        migrations.AddField(
            model_name='healthsymptom',
            name='ai_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthsymptom',
            name='name',
            field=models.CharField(default='General Symptom', max_length=100),
        ),
        migrations.AlterField(
            model_name='healthsymptom',
            name='severity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
